// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlcservice

import (
	"database/sql"
	"time"
)

type Link struct {
	ID         int32
	UserID     int32
	Url        string
	LinkTypeID int32
	Published  bool
}

type LinkType struct {
	ID        int32
	Name      string
	IconClass string
}

type User struct {
	ID             int32
	Username       string
	FirstName      string
	LastName       string
	Email          string
	PasswordHash   string
	RowInserted    time.Time
	RowLastUpdated sql.NullTime
}
